[build-system]
requires = [
    "setuptools>=77.0.3",
    "setuptools-scm>=8.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "mnt.bench"
description = "MNT Bench - An MNT tool for Benchmarking FCN circuits"
readme = "README.md"
authors = [
    { name = "Simon Hofmann", email = "simon.t.hofmann@tum.de" },
]
keywords = ["MNT", "field-coupled nanocomputing", "benchmarking", "performance", "testing"]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dynamic = ["version"]

dependencies = [
    "flask>=3.0.0",
    "humanize>=4.9.0",
    "openpyxl>=3.1.2",
    "packaging>=23.2",
    "pandas>=2.2.0",
    "requests>=2.31.0",
    "tqdm>=4.66.0",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
]

[project.optional-dependencies]
test = ["pytest>=8.2.1"]
coverage = ["mnt.bench[test]", "pytest-cov"]

[project.scripts]
"mnt.bench" = "mnt.bench.main:main"
"mnt-bench" = "mnt.bench.main:main"

[project.urls]
Homepage = "https://github.com/cda-tum/mnt-bench"
"Bug Tracker" = "https://github.com/cda-tum/mnt-bench/issues"
Discussions = "https://github.com/cda-tum/mnt-bench/discussions"
Research = "https://www.cda.cit.tum.de/research/fcn/"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["mnt.bench"]
include-package-data = false

[tool.setuptools.package-data]
"mnt.bench" = [
    "py.typed",
    "static/*.ico",
    "static/*.pdf",
    "static/*.png",
    "static/*.svg",
    "static/files/*.json",
    "templates/*.html",
]

[tool.setuptools_scm]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["-ra", "--strict-config", "--strict-markers"]

[tool.coverage.run]
source = ["mnt.bench"]

[tool.coverage.report]
exclude_also = [
    '\.\.\.',
    'if TYPE_CHECKING:',
]
show_missing = true
skip_empty = true
precision = 1

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
files = ["src", "tests"]
python_version = "3.11"
strict = true
show_error_codes = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
warn_unreachable = true
explicit_package_bases = true
pretty = true

[[tool.mypy.overrides]]
module = ["numpy", "numpy.*", "pandas", "pandas.*"]
follow_imports = "skip"
ignore_missing_imports = true

[tool.ruff]
line-length = 120
namespace-packages = ["src/mnt"]
src = ["src"]
target-version = "py311"

[tool.ruff.lint]
select = [
    "E", "F", "W", # flake8
    "A",           # flake8-builtins
    "B",           # flake8-bugbear
    "I",           # isort
    "ARG",         # flake8-unused-arguments
    "C4",          # flake8-comprehensions
    "EM",          # flake8-errmsg
    "EXE",         # flake8-executable
    "ICN",         # flake8-import-conventions
    "ISC",         # flake8-implicit-str-concat
    "PGH",         # pygrep-hooks
    "PIE",         # flake8-pie
    "PL",          # pylint
    "PT",          # flake8-pytest-style
    "PTH",         # flake8-use-pathlib
    "Q",           # flake8-quotes
    "RET",         # flake8-return
    "RUF",         # Ruff-specific
    "SIM",         # flake8-simplify
    "TCH",         # flake8-type-checking
    "UP",          # pyupgrade
    "YTT",         # flake8-2020
]
ignore = [
    "E501",    # Line too long (Ruff's formatter is enough)
    "ISC001",  # Conflicts with Ruff's formatter
    "PLR2004", # Magic values
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments
    "PLR0915", # Too many statements
    "PLR0917", # Too many positional arguments
]

[tool.codespell]
ignore-words-list = "Wille"
skip = "*.svg,src/mnt/bench/templates/legal.html"
quiet-level = 3
